In [1]:
import pandas as pd

In [2]:
cluster_0_fold0=pd.read_csv('all_preds_cluster_00.csv')
cluster_0_fold1=pd.read_csv('all_preds_cluster_01.csv')
cluster_0_fold2=pd.read_csv('all_preds_cluster_02.csv')

In [3]:
cluster_0_fold0.head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_045_CA_1_validation,0.504440,0.418259,0.369373,0.346330,0.394117,0.436740,0.397235,0.361420,0.346779,...,0.400324,0.424464,0.430793,0.418423,0.380222,0.363875,0.339337,0.364697,0.433134,0.416264
1,HOBBIES_1_046_CA_1_validation,0.971423,0.829429,0.781219,0.787223,0.936438,0.973174,1.141992,1.021465,0.929964,...,0.754245,0.968563,1.026096,0.826383,0.771546,0.735540,0.728661,0.822158,1.039600,1.035336
2,HOBBIES_1_091_CA_1_validation,1.273111,1.023438,1.017776,1.153364,1.343030,1.627356,1.796869,1.198931,1.222996,...,1.279722,1.667970,1.557735,0.982393,0.961881,0.933892,0.973027,1.140143,1.571282,1.587382
3,HOBBIES_1_104_CA_1_validation,0.320361,0.276305,0.265137,0.261109,0.290253,0.336583,0.340037,0.282644,0.288917,...,0.296392,0.383198,0.396213,0.286558,0.277286,0.267934,0.280723,0.297886,0.374168,0.412762
4,HOBBIES_1_125_CA_1_validation,0.583089,0.529603,0.532861,0.529082,0.703729,0.612187,0.593399,0.493159,0.515645,...,0.641145,0.705908,0.601172,0.435498,0.400809,0.430448,0.418633,0.465960,0.667414,0.735329

In [4]:
cluster_0_fold0.shape

(3490, 29)

In [5]:
cluster_0=pd.DataFrame()
cluster_0['id']=cluster_0_fold0['id']
for item in cluster_0_fold0:
    if item!='id':
        cluster_0[item]=(cluster_0_fold0[item]*(1/3))+(cluster_0_fold1[item]*(1/3))+(cluster_0_fold2[item]*(1/3))

In [6]:
cluster_0.head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_045_CA_1_validation,0.396191,0.328018,0.310139,0.298244,0.334829,0.370337,0.371794,0.315859,0.290345,...,0.328932,0.380875,0.407483,0.352494,0.306219,0.304073,0.301601,0.333502,0.389176,0.377438
1,HOBBIES_1_046_CA_1_validation,0.958645,0.817456,0.751748,0.745658,0.907272,1.106560,1.222064,1.047616,0.915084,...,0.762377,0.972033,1.077563,0.827375,0.760704,0.745946,0.733562,0.827094,1.012456,1.036026
2,HOBBIES_1_091_CA_1_validation,1.396791,1.231989,1.114708,1.204720,1.506499,1.768372,2.171316,1.407449,1.348159,...,1.383036,1.843258,1.822382,1.198582,1.108936,1.150726,1.109490,1.325339,1.713806,1.714465
3,HOBBIES_1_104_CA_1_validation,0.346323,0.298730,0.286323,0.266684,0.301073,0.346125,0.390313,0.320105,0.313111,...,0.313336,0.394952,0.413470,0.303833,0.271773,0.289193,0.276659,0.313197,0.402168,0.440310
4,HOBBIES_1_125_CA_1_validation,0.524011,0.487291,0.439063,0.483078,0.614441,0.643883,0.637716,0.438168,0.452871,...,0.503176,0.606518,0.553532,0.420683,0.389691,0.393514,0.401268,0.430974,0.625214,0.674626

In [7]:
cluster_0.shape

(3490, 29)

In [8]:
sub=pd.read_csv('lgb_bycluster_cluster4_noweather_v6.csv')

In [9]:
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(cluster_0['id']))]=list(cluster_0[item])

/Users/shuozhang/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [10]:
sub[sub['id']=='HOBBIES_1_045_CA_1_validation']

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
44,HOBBIES_1_045_CA_1_validation,0.396191,0.328018,0.310139,0.298244,0.334829,0.370337,0.371794,0.315859,0.290345,...,0.328932,0.380875,0.407483,0.352494,0.306219,0.304073,0.301601,0.333502,0.389176,0.377438

In [11]:
sub.to_csv('lgb_bycluster_cluster4_noweather_v6_cluster0.csv',index=False)#0.47654

In [12]:
cluster_1_fold0=pd.read_csv('all_preds_cluster_10.csv')
cluster_1_fold1=pd.read_csv('all_preds_cluster_11.csv')
cluster_1_fold2=pd.read_csv('all_preds_cluster_12.csv')

In [13]:
cluster_1=pd.DataFrame()
cluster_1['id']=cluster_1_fold0['id']
for item in cluster_1_fold0:
    if item!='id':
        cluster_1[item]=(cluster_1_fold0[item]*(1/3))+(cluster_1_fold1[item]*(1/3))+(cluster_1_fold2[item]*(1/3))

In [14]:
sub=pd.read_csv('lgb_bycluster_cluster4_noweather_v6.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(cluster_1['id']))]=list(cluster_1[item])
sub.to_csv('lgb_bycluster_cluster4_noweather_v6_cluster1.csv',index=False)#0.48162

In [15]:
cluster_2_fold0=pd.read_csv('all_preds_cluster_20.csv')
cluster_2_fold1=pd.read_csv('all_preds_cluster_21.csv')
cluster_2_fold2=pd.read_csv('all_preds_cluster_22.csv')

In [16]:
cluster_2=pd.DataFrame()
cluster_2['id']=cluster_2_fold0['id']
for item in cluster_2_fold0:
    if item!='id':
        cluster_2[item]=(cluster_2_fold0[item]*(1/3))+(cluster_2_fold1[item]*(1/3))+(cluster_2_fold2[item]*(1/3))

In [17]:
sub=pd.read_csv('lgb_bycluster_cluster4_noweather_v6.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(cluster_2['id']))]=list(cluster_2[item])
sub.to_csv('lgb_bycluster_cluster4_noweather_v6_cluster2.csv',index=False)#0.47651

In [18]:
cluster_3_fold0=pd.read_csv('all_preds_cluster_30.csv')
cluster_3_fold1=pd.read_csv('all_preds_cluster_31.csv')
cluster_3_fold2=pd.read_csv('all_preds_cluster_32.csv')

In [19]:
cluster_3=pd.DataFrame()
cluster_3['id']=cluster_3_fold0['id']
for item in cluster_3_fold0:
    if item!='id':
        cluster_3[item]=(cluster_3_fold0[item]*(1/3))+(cluster_3_fold1[item]*(1/3))+(cluster_3_fold2[item]*(1/3))

In [20]:
sub=pd.read_csv('lgb_bycluster_cluster4_noweather_v6.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(cluster_3['id']))]=list(cluster_3[item])
sub.to_csv('lgb_bycluster_cluster4_noweather_v6_cluster3.csv',index=False)#0.48030

In [21]:
#replacement

In [22]:
sub=pd.read_csv('lgb_bycluster_cluster4_noweather_v6.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(cluster_2['id']))]=list(cluster_2[item])
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(cluster_0['id']))]=list(cluster_0[item])
sub.to_csv('lgb_bycluster_cluster4_noweather_v6_cluster2_cluster0.csv',index=False)#0.47614