In [1]:
import pandas as pd

In [2]:
foods1_fold0=pd.read_csv('all_preds_FOODS_1_0.csv')
foods1_fold1=pd.read_csv('all_preds_FOODS_1_1.csv')
foods1_fold2=pd.read_csv('all_preds_FOODS_1_2.csv')

In [3]:
foods1_fold0.head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,FOODS_1_001_CA_1_validation,0.769215,0.741214,0.752030,0.776379,1.068959,0.905559,0.837016,1.034885,0.805049,...,0.770985,0.902412,0.931031,0.735985,0.691263,0.687651,0.667178,0.738380,0.984193,0.932003
1,FOODS_1_002_CA_1_validation,0.390462,0.400081,0.394975,0.416529,0.517433,0.467852,0.522405,0.498024,0.517989,...,0.534463,0.694932,0.562970,0.485849,0.442738,0.501087,0.478154,0.471645,0.524686,0.414997
2,FOODS_1_003_CA_1_validation,0.800136,0.690551,0.750118,0.746319,0.851853,0.776900,0.704481,0.773496,0.739220,...,0.832168,0.921311,0.806612,0.802147,0.753295,0.704589,0.719642,0.791964,0.958537,0.797275
3,FOODS_1_004_CA_1_validation,0.011072,0.969784,1.160856,2.388907,4.562267,4.690076,5.111929,3.198475,3.675546,...,5.914523,6.689238,5.705514,4.508884,4.456953,4.600616,4.916415,5.775896,6.618467,6.174644
4,FOODS_1_005_CA_1_validation,1.437252,1.463511,1.593881,1.453171,1.686512,1.808281,1.605767,1.295300,1.248014,...,1.387900,1.553630,1.380102,1.245178,1.207305,1.185631,1.311298,1.340020,1.724435,1.360793

In [4]:
foods1_fold0.shape

(2160, 29)

In [5]:
foods1=pd.DataFrame()
foods1['id']=foods1_fold0['id']
for item in foods1_fold0:
    if item!='id':
        foods1[item]=(foods1_fold0[item]*(1/3))+(foods1_fold1[item]*(1/3))+(foods1_fold2[item]*(1/3))

In [6]:
foods1.head()

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,FOODS_1_001_CA_1_validation,0.762385,0.697632,0.712167,0.736504,1.019728,0.846999,0.844867,0.942745,0.813077,...,0.865455,1.055419,1.010424,0.813099,0.736320,0.729843,0.719147,0.821386,1.093553,0.973467
1,FOODS_1_002_CA_1_validation,0.391390,0.416570,0.392196,0.418434,0.492377,0.451385,0.488399,0.469808,0.523741,...,0.503851,0.616351,0.530459,0.428294,0.423787,0.466101,0.467313,0.504200,0.562017,0.459916
2,FOODS_1_003_CA_1_validation,0.788070,0.692368,0.714204,0.694399,0.857918,0.776284,0.796859,0.807829,0.798927,...,0.827304,0.977150,0.839986,0.752416,0.749246,0.703140,0.686250,0.853296,1.027084,0.881890
3,FOODS_1_004_CA_1_validation,0.020361,1.180185,1.771966,2.965322,4.333468,4.587911,4.729523,3.921311,4.469232,...,6.026499,6.740744,5.958408,4.562442,4.500640,4.739189,4.983091,5.861727,6.894818,6.578852
4,FOODS_1_005_CA_1_validation,1.319422,1.355774,1.435223,1.357467,1.535218,1.479575,1.479672,1.219749,1.225715,...,1.385319,1.515223,1.379783,1.163233,1.127361,1.183702,1.247353,1.355781,1.633077,1.391176

In [7]:
sub=pd.read_csv('lgb_bydept_fe6_noweather.csv')

In [8]:
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(foods1['id']))]=list(foods1[item])

/Users/shuozhang/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [9]:
sub[sub['id']=='FOODS_1_001_CA_1_validation']

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
1612,FOODS_1_001_CA_1_validation,0.762385,0.697632,0.712167,0.736504,1.019728,0.846999,0.844867,0.942745,0.813077,...,0.865455,1.055419,1.010424,0.813099,0.73632,0.729843,0.719147,0.821386,1.093553,0.973467

In [10]:
sub.to_csv('lgb_bydept_fe6_noweather_foods1.csv',index=False)

In [11]:
foods2_fold0=pd.read_csv('all_preds_FOODS_2_0.csv')
foods2_fold1=pd.read_csv('all_preds_FOODS_2_1.csv')
foods2_fold2=pd.read_csv('all_preds_FOODS_2_2.csv')

In [12]:
foods2=pd.DataFrame()
foods2['id']=foods2_fold0['id']
for item in foods2_fold0:
    if item!='id':
        foods2[item]=(foods2_fold0[item]*(1/3))+(foods2_fold1[item]*(1/3))+(foods2_fold2[item]*(1/3))

In [13]:
sub=pd.read_csv('lgb_bydept_fe6_noweather.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(foods2['id']))]=list(foods2[item])
sub.to_csv('lgb_bydept_fe6_noweather_foods2.csv',index=False)

In [14]:
foods3_fold0=pd.read_csv('all_preds_FOODS_3_0.csv')
foods3_fold1=pd.read_csv('all_preds_FOODS_3_1.csv')
foods3_fold2=pd.read_csv('all_preds_FOODS_3_2.csv')
foods3=pd.DataFrame()
foods3['id']=foods3_fold0['id']
for item in foods3_fold0:
    if item!='id':
        foods3[item]=(foods3_fold0[item]*(1/3))+(foods3_fold1[item]*(1/3))+(foods3_fold2[item]*(1/3))
sub=pd.read_csv('lgb_bydept_fe6_noweather.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(foods3['id']))]=list(foods3[item])
sub.to_csv('lgb_bydept_fe6_noweather_foods3.csv',index=False)

In [15]:
hobbies1_fold0=pd.read_csv('all_preds_HOBBIES_1_0.csv')
hobbies1_fold1=pd.read_csv('all_preds_HOBBIES_1_1.csv')
hobbies1_fold2=pd.read_csv('all_preds_HOBBIES_1_2.csv')
hobbies1=pd.DataFrame()
hobbies1['id']=hobbies1_fold0['id']
for item in hobbies1_fold0:
    if item!='id':
        hobbies1[item]=(hobbies1_fold0[item]*(1/3))+(hobbies1_fold1[item]*(1/3))+(hobbies1_fold2[item]*(1/3))
sub=pd.read_csv('lgb_bydept_fe6_noweather.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(hobbies1['id']))]=list(hobbies1[item])
sub.to_csv('lgb_bydept_fe6_noweather_hobbies1.csv',index=False)

In [16]:
hobbies2_fold0=pd.read_csv('all_preds_HOBBIES_2_0.csv')
hobbies2_fold1=pd.read_csv('all_preds_HOBBIES_2_1.csv')
hobbies2_fold2=pd.read_csv('all_preds_HOBBIES_2_2.csv')
hobbies2=pd.DataFrame()
hobbies2['id']=hobbies2_fold0['id']
for item in hobbies2_fold0:
    if item!='id':
        hobbies2[item]=(hobbies2_fold0[item]*(1/3))+(hobbies2_fold1[item]*(1/3))+(hobbies2_fold2[item]*(1/3))
sub=pd.read_csv('lgb_bydept_fe6_noweather.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(hobbies2['id']))]=list(hobbies2[item])
sub.to_csv('lgb_bydept_fe6_noweather_hobbies2.csv',index=False)

In [17]:
household1_fold0=pd.read_csv('all_preds_HOUSEHOLD_1_0.csv')
household1_fold1=pd.read_csv('all_preds_HOUSEHOLD_1_1.csv')
household1_fold2=pd.read_csv('all_preds_HOUSEHOLD_1_2.csv')
household1=pd.DataFrame()
household1['id']=household1_fold0['id']
for item in household1_fold0:
    if item!='id':
        household1[item]=(household1_fold0[item]*(1/3))+(household1_fold1[item]*(1/3))+(household1_fold2[item]*(1/3))
sub=pd.read_csv('lgb_bydept_fe6_noweather.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(household1['id']))]=list(household1[item])
sub.to_csv('lgb_bydept_fe6_noweather_household1.csv',index=False)

In [ ]:
household2_fold0=pd.read_csv('all_preds_HOUSEHOLD_2_0.csv')
household2_fold1=pd.read_csv('all_preds_HOUSEHOLD_2_1.csv')
household2_fold2=pd.read_csv('all_preds_HOUSEHOLD_2_2.csv')
household2=pd.DataFrame()
household2['id']=household2_fold0['id']
for item in household2_fold0:
    if item!='id':
        household[item]=(household1_fold0[item]*(1/3))+(household1_fold1[item]*(1/3))+(household1_fold2[item]*(1/3))
sub=pd.read_csv('lgb_bydept_fe6_noweather.csv')
for item in sub:
    if item!='id':
        sub[item].loc[(sub['id'].isin(household1['id']))]=list(household1[item])
sub.to_csv('lgb_bydept_fe6_noweather_household1.csv',index=False)